version: '3.8'

services:
  javinha-da-massa-1: &javinha
    image: gasparbarancelli/rinha-de-backend-2025:latest
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - HTTP_PORT=8080
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "125MB"

  javinha-da-massa-2:
    <<: *javinha

  load-balancer:
    image: nginx:alpine
    ports:
      - "9999:80"
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"
    depends_on:
      - javinha-da-massa-1
      - javinha-da-massa-2

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true